### ISSUE TITLE
Running Algorithmx in JupyterLab (Requires update for 3.7)

### ISSUE THREAD

**Issue by archienorman11** [algrx/algorithmx-python#1]
Hi- 

Looking for some help getting this tool running in JupiterLab:

I cant seem to get past `"Loading widget..."`

```# !pip freeze

import algorithmx

# Create a Jupyter canvas interface
canvas = algorithmx.jupyter_canvas()

# Set the size of the canvas
canvas.size((300, 200))

# Use the library normally, for example:
canvas.nodes([1, 2]).add()
canvas.edge((1, 2)).add()

# Display the canvas
display(canvas)
```

```
!pip freeze
```

```
...
algorithmx==1.1.2
ipywidgets==7.0.0
jupyter-client==5.3.3
jupyter-core==4.5.0
jupyterhub==1.0.0
jupyterlab==1.2.0
jupyterlab-server==1.0.6
...
```

**Comment by archienorman11** [comment]
I now get:

`Error displaying widget: model not found`

```
[Error] Could not instantiate widget
	(anonymous function) (vendors~main.74576bd817478f8579df.js:1:5615290)
	l (vendors~main.74576bd817478f8579df.js:1:5611748)
	s (vendors~main.74576bd817478f8579df.js:1:5610603)
	promiseReactionJob
[Error] Error: Could not create a model. — utils.js:119
	r (vendors~main.74576bd817478f8579df.js:1:5607600)
	promiseReactionJob
[Error] Exception opening new comm
	(anonymous function) (vendors~main.74576bd817478f8579df.js:1:6201579)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] Error: Module algorithmx-jupyter, semver range ^2.0.0 is not registered as a widget module — manager.js:305
	(anonymous function) (vendors~main.74576bd817478f8579df.js:1:6191768)
	promiseReactionJob
[Error] Error: Module algorithmx-jupyter, semver range ^2.0.0 is not registered as a widget module — manager.js:305
	(anonymous function) (vendors~main.74576bd817478f8579df.js:1:5128156)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] Unhandled Promise Rejection: Error: Module algorithmx-jupyter, semver range ^2.0.0 is not registered as a widget module
	(anonymous function) (vendors~main.74576bd817478f8579df.js:1:5133359)
	promiseReactionJob
```

**Comment by archienorman11** [comment]
It appears the package does not support `python==3.7`, downgrading jupyter worked for me (`jupyter/scipy-notebook:7d427e7a4dde`)

**Comment by alexsocha** [comment]
Thanks for figuring out what the issue was! I'll see if I can add python 3.7 support within the next few days.

**Comment by archienorman11** [comment]
no problem @alexsocha - big fan of this project.

**Comment by alexsocha** [comment]
thanks!

**Comment by archienorman11** [comment]
@alexsocha - do you need a hand adding python 3.7?

**Comment by alexsocha** [comment]
I've been dockerizing the whole thing lately to make the dev environment much nicer and more consistent. It seems that everything works fine under python 3.7 except for the jupyter plugin, so I'll hopefully look over that tomorrow. I think some other packages have had similar issues

**Comment by archienorman11** [comment]
I'm mostly run it as an extension in this docker image: https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook

**Comment by archienorman11** [comment]
Updating @jupyter-widgets/base version might resolve the Jupyter incompatibility issue:

```
"dependencies": {
    "@jupyter-widgets/base": "^1.1.10 || ^2"
  }
```

https://github.com/algrx/algorithmx-python/blob/4c972d3a60390b077e61573ec691d24ab2133a90/js/package.json#L39

**Comment by alexsocha** [comment]
Thanks, I’ll give that a try soon. Been very busy lately!

**Comment by alexsocha** [comment]
I've made all the necessary updates in the latest version, but haven't had much luck in getting the widget to work in JupyterLab. That said, I couldn't even get the standard widgets to work, so it might be an installation issue
